using Newtonsoft.Json;
using System;

namespace AndcultureCode.ZoomClient.Models.Meetings
{
    public class Meeting : BaseObject
    {
        /// <summary>
        /// Zoom Property: uuid
        /// </summary>
        public string Uuid { get; set; }

        /// <summary>
        /// Zoom Property: topic
        /// <para>Meeting topic.</para>
        /// </summary>
        public string Topic { get; set; }

        /// <summary>
        /// Zoom Property: type
        /// <para>Meeting Type:</para>
        /// 1 = Instant meeting.<br/>
        /// 2 = Schedule meeting.<br/>
        /// 3 = Recurring meeting with no fixed time.<br/>
        /// 4 = Recurring meeting with fixed time.<br/>
        /// </summary>
        public MeetingTypes Type { get; set; }

        /// <summary>
        /// Zoom Property: start_time
        /// <para>Meeting start time. Web support two formats for <strong>start_time</strong> - local time and GMT.</para>
        /// <para>The <strong>start_time</strong> should only be used for scheduled and / or recurring webinars with fixed time.</para>
        /// </summary>
        public DateTimeOffset StartTime { get; set; }

        /// <summary>
        /// Zoom Property: duration
        /// <para>Meeting duration (minutes). Used for scheduled meetings only.</para>
        /// </summary>
        public int Duration { get; set; }

        /// <summary>
        /// Zoom Property: timezone
        /// <para>Time zone to format start_time. For example, "America/Los Angeles".
        /// For schedule meetings only. Please reference our 
        /// <see href="https://marketplace.zoom.us/docs/api-reference/other-references/abbreviation-lists#timezones">time zone</see> 
        /// list for supported time zones and their formats.</para>
        /// </summary>
        public string Timezone { get; set; }

        /// <summary>
        /// Zoom Property: password
        /// <para>Meeting password. Password may only contain the following characters: [a-z A-Z 0-9 @ - _ * !]
        /// and can have a maximum of 10 characters.</para>
        /// <para><strong>Note:</strong> If the account owner or the admin has configured
        /// <see href="https://support.zoom.us/hc/en-us/articles/360033559832-Meeting-and-webinar-passwords#h_a427384b-e383-4f80-864d-794bf0a37604">minimum passcode requirement settings</see>,
        /// the passcode value provided here must meet those requirements.
        /// </para>
        /// <para>If “Require a password when scheduling new meetings” setting has been 
        /// <strong>enabled and
        /// <see href="https://support.zoom.us/hc/en-us/articles/115005269866-Using-Tiered-Settings#locked">locked</see></strong> 
        /// for the user, the password field will be autogenerated in the response even if it is not provided in the API request.
        /// </para>
        /// </summary>
        public string Password { get; set; }

        /// <summary>
        /// Zoom Property: agenda
        /// <para>Meeting description.</para>
        /// </summary>
        public string Agenda { get; set; }

        /// <summary>
        /// Zoom Property: start_url
        /// <para>URL to start the meeting. This URL should only be used by the host of the meeting and 
        /// <strong>should not be shared with anyone other than the host</strong> of the meeting as anyone
        /// with this URL will be able to login to the Zoom Client as the host of the meeting.</para>
        /// </summary>
        public string StartUrl { get; set; }

        /// <summary>
        /// Zoom Property: join_url
        /// <para>URL for participants to join the meeting. 
        /// This URL should only be shared with users that you would like to invite for the meeting.</para>
        /// </summary>
        public string JoinUrl { get; set; }

        /// <summary>
        /// Zoom Property h323_password
        /// <para>H.323/SIP room system password.</para>
        /// </summary>
        public string H323Password { get; set; }

        /// <summary>
        /// Zoom Property: pmi
        /// <para>Personal Meeting Id. Only used for schedule meetings and recurring meetings with no fixed time.</para>
        /// </summary>
        [JsonProperty("pmi")]
        public string PersonalMeetingId { get; set; }

        /// <summary>
        /// Zoom Property: assistant_id
        /// <para>Unique identifier for the scheduler who scheduled this meeting on behalf of the host.
        /// This field is only returned if you used "schedule_for" option in the 
        /// <see href="https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate">
        /// Create a Meeting API request</see>.</para>
        /// </summary>
        public string AssistantId { get; set; }

        /// <summary>
        /// Zoom Property: host_email
        /// <para>Email address of the meeting host.</para>
        /// </summary>
        public string HostEmail { get; set; }

        /// <summary>
        /// Zoom Property: created_at
        /// <para>The date and time at which this meeting was created.</para>
        /// </summary>
        public DateTimeOffset? CreatedTime { get; set; }

        /// <summary>
        /// Zoom Property: occurrences
        /// </summary>
        public MeetingOccurrence[] Occurrences { get; set; }

        /// <summary>
        /// Zoom Property: tracking_fields
        /// </summary>
        public MeetingTrackingField[] TrackingFields { get; set; }

        /// <summary>
        /// Zoom Property: recurrence
        /// <para>Recurrence object. Use this object only for a meeting with a type 8 
        /// i.e., a recurring meeting with fixed time.</para>
        /// </summary>
        public MeetingRecurrence Recurrence { get; set; }

        /// <summary>
        /// Zoom Property: settings
        /// </summary>
        public MeetingSettings Settings { get; set; }
    }
}
